### ISSUE TITLE
Background of images

### ISSUE THREAD

**Issue by angerangel** [blthemes/Blekathlon#11]
Hi,
if I use small or transparent images, the theme add a black background, how can I change the background color?

**Comment by dimobelov** [comment]
Hi, @angerangel 
try to change this line
https://github.com/blthemes/Blekathlon/blob/cd4c2c610219a2f60e1f79ae8b623232fe2f482c/php/home.php#L19
```
<?php $coverImage = $helper->get_thumb();?>
```
to
```
<?php $coverImage = $page->coverImage();?>
```

**Comment by angerangel** [comment]
It works, thank you!
