### ISSUE TITLE
[bug] dis[lay logo and related icons

### ISSUE THREAD

**Issue by abdulhalim** [blthemes/Blekathlon#4]
There is a bug in the lib/helper.php file, I guess related to line 16 and 34.
It returns an icon for related posts and logo image, it should be the replacement for missing photo.
///
Edit
It's OK online, I had a problem only on the localhost

**Comment by dimobelov** [comment]
@abdulhalim , there have some checks for localhost, but now devs have so many options to change default settings for this :)
https://github.com/blthemes/Blekathlon/blob/99683d28f20a0d250a4911f62b8cd2dac3e0bff0/php/lib/helper.php#L12
https://github.com/blthemes/Blekathlon/blob/99683d28f20a0d250a4911f62b8cd2dac3e0bff0/php/lib/helper.php#L30
