### ISSUE TITLE
Search - add focus on search text field plus a couple more changes.

### ISSUE THREAD

**Issue by BlakesHeaven** [blthemes/Blekathlon#5]
I was about to add the extra plugin to facilitate the search in the previous theme so I'm liking the built-in search function.

Can I suggest a few changes:
1. Add focus on search text field instead of having to click it first.
2. Change minimum number of characters from four to three to initiate the search.
3. Change the search tip text to state how many characters are needed to initiate the search.

**Comment by dimobelov** [comment]
https://github.com/blthemes/Blekathlon/releases/tag/3.8.1
