### ISSUE TITLE
Case sensitive search inconsistencies

### ISSUE THREAD

**Issue by BlakesHeaven** [blthemes/Blekathlon#6]
Hi, can you check if you think this is a bug?

In the screenshot below, you can see I have typed, "The dramatic lime st" and all seems OK, however, I have noticed that there are some inconsistencies.

> ![image](https://user-images.githubusercontent.com/37149377/54959021-a6258c00-4f4f-11e9-9be1-e1fdba58ca5f.png)

Firstly, can you please clarify if the search is case sensitive or not?

- I believe it is, but would prefer it to be case **in**sencitive, eg "Dramatic", should find both "Dramatic" and "**d**ramatic"
If I only type "dram", I get results, but if I type "matic", I get nothing back

Thanks.

**Comment by dimobelov** [comment]
https://github.com/blthemes/Blekathlon/releases/tag/3.8.1
