### ISSUE TITLE
Language does not refresh properly after clearing search

### ISSUE THREAD

**Issue by BlakesHeaven** [blthemes/Blekathlon#7]
Hi, I have been trying to update the text that appears and noticed that after clearing the search the language text is not pulled through properly.

Below you see what I changed the text to...

> ![image](https://user-images.githubusercontent.com/37149377/54960093-3d401300-4f53-11e9-9513-8946bac3c420.png)

After a successful search, I click the cross to clear the results and I get the following, which returns the code place-holder.

> ![image](https://user-images.githubusercontent.com/37149377/54960167-76788300-4f53-11e9-82d6-652953aa17d2.png)

In bundle.min.js
`$( ".search-result-meta" ).html( "type-to-start-searching" );`

In en.json
`"type-to-start-searching": "Type 4 or more letters above to start searching",`

**Comment by dimobelov** [comment]
In js messages are hardcoded now. In next version they'll be in the language files.
https://github.com/blthemes/DevTheme/issues/4

**Comment by dimobelov** [comment]
https://github.com/blthemes/Blekathlon/releases/tag/3.8.1

**Comment by BlakesHeaven** [comment]
Thanks for all you have done in this release.
