### ISSUE TITLE
Magnifier Search - Results OK, but goto page fails when on /tag/ or /category/, etc

### ISSUE THREAD

**Issue by BlakesHeaven** [blthemes/Blekathlon#8]
Firstly, it is great to see sidebar plugins appearing in the side menu!

Steps to reproduce the issue:
1. Add either Category or Tags menu
2. Make a selection from either
3. Now search using Magnifier - results are good
4. Click one of the results
5. Get page not found.

**Comment by dimobelov** [comment]
Hah, nice bug. Will be fixed in the next version :) Thanks!

**Comment by dimobelov** [comment]
Fixed in 3.9.0

**Comment by BlakesHeaven** [comment]
Thanks. :-)
